// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *About Page → Feature Skill*
 */
export interface AboutPageDocumentDataFeatureSkillItem {
  /**
   * Skill field in *About Page → Feature Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.feature_skill[].skill
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill: prismic.KeyTextField;
}

type AboutPageDocumentDataSlicesSlice = AboutSkillSlice | AboutRichtextSlice;

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
  /**
   * Label Big Text  field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.label_big_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_big_text: prismic.KeyTextField;

  /**
   * Name field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Nickname field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.nickname
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nickname: prismic.KeyTextField;

  /**
   * Feature Skill field in *About Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.feature_skill[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_skill: prismic.GroupField<
    Simplify<AboutPageDocumentDataFeatureSkillItem>
  >;

  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
   * Meta Title field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

type ArchivePageDocumentDataSlicesSlice = ArchiveListingSlice;

/**
 * Content for Archive Page documents
 */
interface ArchivePageDocumentData {
  /**
   * Max Items (Total Item in Layout) field in *Archive Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.max_items
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  max_items: prismic.NumberField;

  /**
   * Columns Number field in *Archive Page*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.columns_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns_number: prismic.NumberField;

  /**
   * Slice Zone field in *Archive Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArchivePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Archive Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: archive_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Archive Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: archive_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Archive Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Archive Page document from Prismic
 *
 * - **API ID**: `archive_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchivePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArchivePageDocumentData>,
    "archive_page",
    Lang
  >;

type GlobalSettingDocumentDataSlicesSlice = never;

/**
 * Content for Global Setting documents
 */
interface GlobalSettingDocumentData {
  /**
   * Slice Zone field in *Global Setting*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: global_setting.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<GlobalSettingDocumentDataSlicesSlice> /**
   * Meta Title field in *Global Setting*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: global_setting.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Global Setting*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: global_setting.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Global Setting*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: global_setting.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Global Setting document from Prismic
 *
 * - **API ID**: `global_setting`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlobalSettingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GlobalSettingDocumentData>,
    "global_setting",
    Lang
  >;

/**
 * Item in *Header → Navigation*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * Page field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].page
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | ProjectListingSlice
  | TextBlockSlice
  | ImageBlockSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Listing Order Project → List Ortder Projects*
 */
export interface ListingOrderProjectDocumentDataListOrtderProjectsItem {
  /**
   * Project field in *Listing Order Project → List Ortder Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: listing_order_project.list_ortder_projects[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [{ id: "project"; fields: ["title", "work_detail_image", "thumbnail"] }]
  >;
}

/**
 * Content for Listing Order Project documents
 */
interface ListingOrderProjectDocumentData {
  /**
   * List Ortder Projects field in *Listing Order Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: listing_order_project.list_ortder_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_ortder_projects: prismic.GroupField<
    Simplify<ListingOrderProjectDocumentDataListOrtderProjectsItem>
  >;
}

/**
 * Listing Order Project document from Prismic
 *
 * - **API ID**: `listing_order_project`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ListingOrderProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ListingOrderProjectDocumentData>,
    "listing_order_project",
    Lang
  >;

type ProjectDocumentDataSlicesSlice = ProjectSliceSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Role field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role: prismic.RichTextField;

  /**
   * Challenge field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.challenge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge: prismic.RichTextField;

  /**
   * Scope of Work field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.responsibilities
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  responsibilities: prismic.RichTextField;

  /**
   * Live Link URL field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.live_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Home Thumbnail field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Home Media(Video) field in *Project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project.feature_media
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  feature_media: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Work Detail Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.work_detail_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  work_detail_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

type VirtuallightPageDocumentDataSlicesSlice =
  | SpacingSlice
  | VituralightSliceSlice
  | VituralightRecognizedPotentialSlice
  | VirtualLightCompSlice
  | TextBlockSlice;

/**
 * Content for VirtualLight Page documents
 */
interface VirtuallightPageDocumentData {
  /**
   * Label Big Text field in *VirtualLight Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: virtuallight_page.label_big_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_big_text: prismic.KeyTextField;

  /**
   * Image Under Title field in *VirtualLight Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: virtuallight_page.image_under_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_under_title: prismic.ImageField<never>;

  /**
   * Slice Zone field in *VirtualLight Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: virtuallight_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<VirtuallightPageDocumentDataSlicesSlice> /**
   * Meta Title field in *VirtualLight Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: virtuallight_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *VirtualLight Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: virtuallight_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *VirtualLight Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: virtuallight_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * VirtualLight Page document from Prismic
 *
 * - **API ID**: `virtuallight_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VirtuallightPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VirtuallightPageDocumentData>,
    "virtuallight_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | ArchivePageDocument
  | GlobalSettingDocument
  | HeaderDocument
  | HomePageDocument
  | ListingOrderProjectDocument
  | ProjectDocument
  | VirtuallightPageDocument;

/**
 * Primary content in *AboutRichtext → Default → Primary*
 */
export interface AboutRichtextSliceDefaultPrimary {
  /**
   * Title field in *AboutRichtext → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_richtext.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AboutRichtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_richtext.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutRichtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutRichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutRichtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutRichtext*
 */
type AboutRichtextSliceVariation = AboutRichtextSliceDefault;

/**
 * AboutRichtext Shared Slice
 *
 * - **API ID**: `about_richtext`
 * - **Description**: AboutRichtext
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutRichtextSlice = prismic.SharedSlice<
  "about_richtext",
  AboutRichtextSliceVariation
>;

/**
 * Item in *AboutSkill → Default → Primary → Skill List*
 */
export interface AboutSkillSliceDefaultPrimarySkillListItem {
  /**
   * Skill field in *AboutSkill → Default → Primary → Skill List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.default.primary.skill_list[].skill
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill: prismic.KeyTextField;
}

/**
 * Item in *AboutSkill → 2 Columns → Primary → Skill List Left*
 */
export interface AboutSkillSlice2ColumnsPrimarySkillListLeftItem {
  /**
   * Skill field in *AboutSkill → 2 Columns → Primary → Skill List Left*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.2Columns.primary.skill_list_left[].skill
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill: prismic.KeyTextField;
}

/**
 * Item in *AboutSkill → 2 Columns → Primary → Skill List Right*
 */
export interface AboutSkillSlice2ColumnsPrimarySkillListRightItem {
  /**
   * Skill field in *AboutSkill → 2 Columns → Primary → Skill List Right*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.2Columns.primary.skill_list_right[].skill
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  skill: prismic.KeyTextField;
}

/**
 * Primary content in *AboutSkill → Default → Primary*
 */
export interface AboutSkillSliceDefaultPrimary {
  /**
   * Title field in *AboutSkill → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Skill List field in *AboutSkill → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.default.primary.skill_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  skill_list: prismic.GroupField<
    Simplify<AboutSkillSliceDefaultPrimarySkillListItem>
  >;
}

/**
 * Default variation for AboutSkill Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSkillSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSkillSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AboutSkill → 2 Columns → Primary*
 */
export interface AboutSkillSlice2ColumnsPrimary {
  /**
   * Title field in *AboutSkill → 2 Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.2Columns.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Skill List Left field in *AboutSkill → 2 Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.2Columns.primary.skill_list_left[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  skill_list_left: prismic.GroupField<
    Simplify<AboutSkillSlice2ColumnsPrimarySkillListLeftItem>
  >;

  /**
   * Skill List Right field in *AboutSkill → 2 Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_skill.2Columns.primary.skill_list_right[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  skill_list_right: prismic.GroupField<
    Simplify<AboutSkillSlice2ColumnsPrimarySkillListRightItem>
  >;
}

/**
 * 2 Columns variation for AboutSkill Slice
 *
 * - **API ID**: `2Columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSkillSlice2Columns = prismic.SharedSliceVariation<
  "2Columns",
  Simplify<AboutSkillSlice2ColumnsPrimary>,
  never
>;

/**
 * Slice variation for *AboutSkill*
 */
type AboutSkillSliceVariation =
  | AboutSkillSliceDefault
  | AboutSkillSlice2Columns;

/**
 * AboutSkill Shared Slice
 *
 * - **API ID**: `about_skill`
 * - **Description**: AboutSkill
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSkillSlice = prismic.SharedSlice<
  "about_skill",
  AboutSkillSliceVariation
>;

/**
 * Item in *ArchiveListing → Masonry Layout → Primary → List Media(Image, Video)*
 */
export interface ArchiveListingSliceDefaultPrimaryListMediaItem {
  /**
   * Media field in *ArchiveListing → Masonry Layout → Primary → List Media(Image, Video)*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Alternative Text to detect
   * - **API ID Path**: archive_listing.default.primary.list_media[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *ArchiveListing → Masonry Layout → Primary*
 */
export interface ArchiveListingSliceDefaultPrimary {
  /**
   * List Media(Image, Video) field in *ArchiveListing → Masonry Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: archive_listing.default.primary.list_media[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_media: prismic.GroupField<
    Simplify<ArchiveListingSliceDefaultPrimaryListMediaItem>
  >;
}

/**
 * Masonry Layout variation for ArchiveListing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchiveListingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArchiveListingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArchiveListing*
 */
type ArchiveListingSliceVariation = ArchiveListingSliceDefault;

/**
 * ArchiveListing Shared Slice
 *
 * - **API ID**: `archive_listing`
 * - **Description**: ArchiveListing
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArchiveListingSlice = prismic.SharedSlice<
  "archive_listing",
  ArchiveListingSliceVariation
>;

/**
 * Primary content in *ImageBlock → Image Full Viewport → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * Image field in *ImageBlock → Image Full Viewport → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image Full Viewport variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Item in *ProjectListing → Default → Primary → Feature Projects*
 */
export interface ProjectListingSliceDefaultPrimaryFeatureProjectsItem {
  /**
   * Aspect Ratio field in *ProjectListing → Default → Primary → Feature Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.default.primary.feature_projects[].aspect_ratio
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  aspect_ratio: prismic.NumberField;

  /**
   * Project field in *ProjectListing → Default → Primary → Feature Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.default.primary.feature_projects[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [{ id: "project"; fields: ["title", "thumbnail", "feature_media"] }]
  >;
}

/**
 * Primary content in *ProjectListing → Default → Primary*
 */
export interface ProjectListingSliceDefaultPrimary {
  /**
   * Feature Projects field in *ProjectListing → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_listing.default.primary.feature_projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_projects: prismic.GroupField<
    Simplify<ProjectListingSliceDefaultPrimaryFeatureProjectsItem>
  >;
}

/**
 * Default variation for ProjectListing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectListingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectListingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectListing*
 */
type ProjectListingSliceVariation = ProjectListingSliceDefault;

/**
 * ProjectListing Shared Slice
 *
 * - **API ID**: `project_listing`
 * - **Description**: ProjectListing
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectListingSlice = prismic.SharedSlice<
  "project_listing",
  ProjectListingSliceVariation
>;

/**
 * Item in *ProjectSlice → Slide List → Primary → List Images*
 */
export interface ProjectSliceSliceListImagePrimaryListImagesItem {
  /**
   * Image field in *ProjectSlice → Slide List → Primary → List Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.listImage.primary.list_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *ProjectSlice → Detail → Primary → List Content*
 */
export interface ProjectSliceSliceDetailPrimaryListContentItem {
  /**
   * Title field in *ProjectSlice → Detail → Primary → List Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.detail.primary.list_content[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProjectSlice → Detail → Primary → List Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.detail.primary.list_content[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *ProjectSlice → Image GridLayout → Primary → List Image*
 */
export interface ProjectSliceSliceGridLayoutPrimaryListImageItem {
  /**
   * Image field in *ProjectSlice → Image GridLayout → Primary → List Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.gridLayout.primary.list_image[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *ProjectSlice → Video GridLayout → Primary → List Video*
 */
export interface ProjectSliceSliceVideoGridLayoutPrimaryListVideoItem {
  /**
   * Media field in *ProjectSlice → Video GridLayout → Primary → List Video*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.videoGridLayout.primary.list_video[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *ProjectSlice → Video → Primary*
 */
export interface ProjectSliceSliceDefaultPrimary {
  /**
   * Video field in *ProjectSlice → Video → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Video variation for ProjectSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Single Image → Primary*
 */
export interface ProjectSliceSliceSingleImagePrimary {
  /**
   * Image field in *ProjectSlice → Single Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.singleImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Single Image variation for ProjectSlice Slice
 *
 * - **API ID**: `singleImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceSingleImage = prismic.SharedSliceVariation<
  "singleImage",
  Simplify<ProjectSliceSliceSingleImagePrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Slide List → Primary*
 */
export interface ProjectSliceSliceListImagePrimary {
  /**
   * List Images field in *ProjectSlice → Slide List → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.listImage.primary.list_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_images: prismic.GroupField<
    Simplify<ProjectSliceSliceListImagePrimaryListImagesItem>
  >;
}

/**
 * Slide List variation for ProjectSlice Slice
 *
 * - **API ID**: `listImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceListImage = prismic.SharedSliceVariation<
  "listImage",
  Simplify<ProjectSliceSliceListImagePrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Detail → Primary*
 */
export interface ProjectSliceSliceDetailPrimary {
  /**
   * Big Title field in *ProjectSlice → Detail → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.detail.primary.big_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  big_title: prismic.KeyTextField;

  /**
   * List Content field in *ProjectSlice → Detail → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.detail.primary.list_content[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_content: prismic.GroupField<
    Simplify<ProjectSliceSliceDetailPrimaryListContentItem>
  >;
}

/**
 * Detail variation for ProjectSlice Slice
 *
 * - **API ID**: `detail`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceDetail = prismic.SharedSliceVariation<
  "detail",
  Simplify<ProjectSliceSliceDetailPrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Embed Video → Primary*
 */
export interface ProjectSliceSliceEmbedVideoPrimary {
  /**
   * Embed field in *ProjectSlice → Embed Video → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.embedVideo.primary.embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;
}

/**
 * Embed Video variation for ProjectSlice Slice
 *
 * - **API ID**: `embedVideo`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceEmbedVideo = prismic.SharedSliceVariation<
  "embedVideo",
  Simplify<ProjectSliceSliceEmbedVideoPrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Image GridLayout → Primary*
 */
export interface ProjectSliceSliceGridLayoutPrimary {
  /**
   * Number of columns field in *ProjectSlice → Image GridLayout → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2
   * - **API ID Path**: project_slice.gridLayout.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * List Image field in *ProjectSlice → Image GridLayout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.gridLayout.primary.list_image[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_image: prismic.GroupField<
    Simplify<ProjectSliceSliceGridLayoutPrimaryListImageItem>
  >;
}

/**
 * Image GridLayout variation for ProjectSlice Slice
 *
 * - **API ID**: `gridLayout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceGridLayout = prismic.SharedSliceVariation<
  "gridLayout",
  Simplify<ProjectSliceSliceGridLayoutPrimary>,
  never
>;

/**
 * Primary content in *ProjectSlice → Video GridLayout → Primary*
 */
export interface ProjectSliceSliceVideoGridLayoutPrimary {
  /**
   * Number of columns field in *ProjectSlice → Video GridLayout → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2
   * - **API ID Path**: project_slice.videoGridLayout.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * List Video field in *ProjectSlice → Video GridLayout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_slice.videoGridLayout.primary.list_video[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_video: prismic.GroupField<
    Simplify<ProjectSliceSliceVideoGridLayoutPrimaryListVideoItem>
  >;
}

/**
 * Video GridLayout variation for ProjectSlice Slice
 *
 * - **API ID**: `videoGridLayout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSliceVideoGridLayout = prismic.SharedSliceVariation<
  "videoGridLayout",
  Simplify<ProjectSliceSliceVideoGridLayoutPrimary>,
  never
>;

/**
 * Slice variation for *ProjectSlice*
 */
type ProjectSliceSliceVariation =
  | ProjectSliceSliceDefault
  | ProjectSliceSliceSingleImage
  | ProjectSliceSliceListImage
  | ProjectSliceSliceDetail
  | ProjectSliceSliceEmbedVideo
  | ProjectSliceSliceGridLayout
  | ProjectSliceSliceVideoGridLayout;

/**
 * ProjectSlice Shared Slice
 *
 * - **API ID**: `project_slice`
 * - **Description**: ProjectSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectSliceSlice = prismic.SharedSlice<
  "project_slice",
  ProjectSliceSliceVariation
>;

/**
 * Primary content in *Spacing → Default → Primary*
 */
export interface SpacingSliceDefaultPrimary {
  /**
   * Spacing field in *Spacing → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 10
   * - **API ID Path**: spacing.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  spacing: prismic.SelectField<
    "10" | "20" | "30" | "40" | "50" | "60" | "70" | "80" | "90",
    "filled"
  >;
}

/**
 * Default variation for Spacing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacing*
 */
type SpacingSliceVariation = SpacingSliceDefault;

/**
 * Spacing Shared Slice
 *
 * - **API ID**: `spacing`
 * - **Description**: Spacing
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacingSlice = prismic.SharedSlice<
  "spacing",
  SpacingSliceVariation
>;

/**
 * Item in *TextBlock → Resume → Primary → List Skill*
 */
export interface TextBlockSliceResumePrimaryListSkillItem {
  /**
   * Title field in *TextBlock → Resume → Primary → List Skill*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_skill[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TextBlock → Resume → Primary → List Skill*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_skill[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *TextBlock → Resume → Primary → List Contact*
 */
export interface TextBlockSliceResumePrimaryListContactItem {
  /**
   * Label field in *TextBlock → Resume → Primary → List Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_contact[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Content field in *TextBlock → Resume → Primary → List Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_contact[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *TextBlock → Summary → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Richtext field in *TextBlock → Summary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.richtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  richtext: prismic.RichTextField;
}

/**
 * Summary variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextBlock → Resume → Primary*
 */
export interface TextBlockSliceResumePrimary {
  /**
   * Preamble field in *TextBlock → Resume → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.preamble
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  preamble: prismic.RichTextField;

  /**
   * Label Skill field in *TextBlock → Resume → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Skill
   * - **API ID Path**: text_block.resume.primary.label_skill
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_skill: prismic.KeyTextField;

  /**
   * List Skill field in *TextBlock → Resume → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_skill[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_skill: prismic.GroupField<
    Simplify<TextBlockSliceResumePrimaryListSkillItem>
  >;

  /**
   * Label Contact field in *TextBlock → Resume → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact
   * - **API ID Path**: text_block.resume.primary.label_contact
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label_contact: prismic.KeyTextField;

  /**
   * List Contact field in *TextBlock → Resume → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.resume.primary.list_contact[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_contact: prismic.GroupField<
    Simplify<TextBlockSliceResumePrimaryListContactItem>
  >;
}

/**
 * Resume variation for TextBlock Slice
 *
 * - **API ID**: `resume`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceResume = prismic.SharedSliceVariation<
  "resume",
  Simplify<TextBlockSliceResumePrimary>,
  never
>;

/**
 * Primary content in *TextBlock → Richtext → Primary*
 */
export interface TextBlockSliceRichtextPrimary {
  /**
   * Richtext field in *TextBlock → Richtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.richtext.primary.richtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  richtext: prismic.RichTextField;
}

/**
 * Richtext variation for TextBlock Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSliceRichtext = prismic.SharedSliceVariation<
  "richtext",
  Simplify<TextBlockSliceRichtextPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation =
  | TextBlockSliceDefault
  | TextBlockSliceResume
  | TextBlockSliceRichtext;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Item in *VirtualLightComp → Default → Primary → List Image*
 */
export interface VirtualLightCompSliceDefaultPrimaryListImageItem {
  /**
   * Image field in *VirtualLightComp → Default → Primary → List Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.list_image[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *VirtualLightComp → Default → Primary → List Internal Media*
 */
export interface VirtualLightCompSliceDefaultPrimaryListInternalMediaItem {
  /**
   * Media field in *VirtualLightComp → Default → Primary → List Internal Media*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Description for detect
   * - **API ID Path**: virtual_light_comp.default.primary.list_internal_media[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Item in *VirtualLightComp → Default → Primary → List Embed Media*
 */
export interface VirtualLightCompSliceDefaultPrimaryListEmbedMediaItem {
  /**
   * Media field in *VirtualLightComp → Default → Primary → List Embed Media*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.list_embed_media[].media
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  media: prismic.EmbedField;
}

/**
 * Item in *VirtualLightComp → Grid Layout → Primary → List Media(Image, Video)*
 */
export interface VirtualLightCompSliceGridLayoutPrimaryListMediaItem {
  /**
   * Media field in *VirtualLightComp → Grid Layout → Primary → List Media(Image, Video)*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Description for detect
   * - **API ID Path**: virtual_light_comp.gridLayout.primary.list_media[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *VirtualLightComp → Default → Primary*
 */
export interface VirtualLightCompSliceDefaultPrimary {
  /**
   * Description field in *VirtualLightComp → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * List Image field in *VirtualLightComp → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.list_image[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_image: prismic.GroupField<
    Simplify<VirtualLightCompSliceDefaultPrimaryListImageItem>
  >;

  /**
   * List Internal Media field in *VirtualLightComp → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.list_internal_media[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_internal_media: prismic.GroupField<
    Simplify<VirtualLightCompSliceDefaultPrimaryListInternalMediaItem>
  >;

  /**
   * List Embed Media field in *VirtualLightComp → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.default.primary.list_embed_media[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_embed_media: prismic.GroupField<
    Simplify<VirtualLightCompSliceDefaultPrimaryListEmbedMediaItem>
  >;
}

/**
 * Default variation for VirtualLightComp Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VirtualLightCompSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VirtualLightCompSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *VirtualLightComp → Grid Layout → Primary*
 */
export interface VirtualLightCompSliceGridLayoutPrimary {
  /**
   * Description field in *VirtualLightComp → Grid Layout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.gridLayout.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * List Media(Image, Video) field in *VirtualLightComp → Grid Layout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: virtual_light_comp.gridLayout.primary.list_media[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_media: prismic.GroupField<
    Simplify<VirtualLightCompSliceGridLayoutPrimaryListMediaItem>
  >;
}

/**
 * Grid Layout variation for VirtualLightComp Slice
 *
 * - **API ID**: `gridLayout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VirtualLightCompSliceGridLayout = prismic.SharedSliceVariation<
  "gridLayout",
  Simplify<VirtualLightCompSliceGridLayoutPrimary>,
  never
>;

/**
 * Slice variation for *VirtualLightComp*
 */
type VirtualLightCompSliceVariation =
  | VirtualLightCompSliceDefault
  | VirtualLightCompSliceGridLayout;

/**
 * VirtualLightComp Shared Slice
 *
 * - **API ID**: `virtual_light_comp`
 * - **Description**: VirtualLightComp
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VirtualLightCompSlice = prismic.SharedSlice<
  "virtual_light_comp",
  VirtualLightCompSliceVariation
>;

/**
 * Item in *VituralightRecognizedPotential → Default → Primary → List Member*
 */
export interface VituralightRecognizedPotentialSliceDefaultPrimaryListMemberItem {
  /**
   * Name field in *VituralightRecognizedPotential → Default → Primary → List Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.list_member[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *VituralightRecognizedPotential → Default → Primary → List Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.list_member[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *VituralightRecognizedPotential → Default → Primary*
 */
export interface VituralightRecognizedPotentialSliceDefaultPrimary {
  /**
   * Top paragraph field in *VituralightRecognizedPotential → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.top_paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  top_paragraph: prismic.RichTextField;

  /**
   * Description of List field in *VituralightRecognizedPotential → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.description_of_list
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description_of_list: prismic.KeyTextField;

  /**
   * List Member field in *VituralightRecognizedPotential → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.list_member[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_member: prismic.GroupField<
    Simplify<VituralightRecognizedPotentialSliceDefaultPrimaryListMemberItem>
  >;

  /**
   * Last Description  field in *VituralightRecognizedPotential → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_recognized_potential.default.primary.last_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  last_description: prismic.RichTextField;
}

/**
 * Default variation for VituralightRecognizedPotential Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightRecognizedPotentialSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<VituralightRecognizedPotentialSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *VituralightRecognizedPotential*
 */
type VituralightRecognizedPotentialSliceVariation =
  VituralightRecognizedPotentialSliceDefault;

/**
 * VituralightRecognizedPotential Shared Slice
 *
 * - **API ID**: `vituralight_recognized_potential`
 * - **Description**: VituralightRecognizedPotential
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightRecognizedPotentialSlice = prismic.SharedSlice<
  "vituralight_recognized_potential",
  VituralightRecognizedPotentialSliceVariation
>;

/**
 * Item in *VituralightSlice → GridLayout → Primary → List Media(Image, Video)*
 */
export interface VituralightSliceSliceGridLayoutPrimaryListMediaItem {
  /**
   * Media field in *VituralightSlice → GridLayout → Primary → List Media(Image, Video)*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.gridLayout.primary.list_media[].media
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  media: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *VituralightSlice → Richtext → Primary*
 */
export interface VituralightSliceSliceDefaultPrimary {
  /**
   * Richtext field in *VituralightSlice → Richtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.default.primary.richtext
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  richtext: prismic.RichTextField;
}

/**
 * Richtext variation for VituralightSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VituralightSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *VituralightSlice → GridLayout → Primary*
 */
export interface VituralightSliceSliceGridLayoutPrimary {
  /**
   * Number of columns field in *VituralightSlice → GridLayout → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.gridLayout.primary.number_of_columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number_of_columns: prismic.NumberField;

  /**
   * List Media(Image, Video) field in *VituralightSlice → GridLayout → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.gridLayout.primary.list_media[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  list_media: prismic.GroupField<
    Simplify<VituralightSliceSliceGridLayoutPrimaryListMediaItem>
  >;
}

/**
 * GridLayout variation for VituralightSlice Slice
 *
 * - **API ID**: `gridLayout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightSliceSliceGridLayout = prismic.SharedSliceVariation<
  "gridLayout",
  Simplify<VituralightSliceSliceGridLayoutPrimary>,
  never
>;

/**
 * Primary content in *VituralightSlice → Embed → Primary*
 */
export interface VituralightSliceSliceEmbedPrimary {
  /**
   * Embed field in *VituralightSlice → Embed → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.embed.primary.embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;
}

/**
 * Embed variation for VituralightSlice Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightSliceSliceEmbed = prismic.SharedSliceVariation<
  "embed",
  Simplify<VituralightSliceSliceEmbedPrimary>,
  never
>;

/**
 * Primary content in *VituralightSlice → 2Columns → Primary*
 */
export interface VituralightSliceSlice2ColumnsPrimary {
  /**
   * Title field in *VituralightSlice → 2Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.2Columns.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *VituralightSlice → 2Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vituralight_slice.2Columns.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * 2Columns variation for VituralightSlice Slice
 *
 * - **API ID**: `2Columns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightSliceSlice2Columns = prismic.SharedSliceVariation<
  "2Columns",
  Simplify<VituralightSliceSlice2ColumnsPrimary>,
  never
>;

/**
 * Slice variation for *VituralightSlice*
 */
type VituralightSliceSliceVariation =
  | VituralightSliceSliceDefault
  | VituralightSliceSliceGridLayout
  | VituralightSliceSliceEmbed
  | VituralightSliceSlice2Columns;

/**
 * VituralightSlice Shared Slice
 *
 * - **API ID**: `vituralight_slice`
 * - **Description**: VituralightSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VituralightSliceSlice = prismic.SharedSlice<
  "vituralight_slice",
  VituralightSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataFeatureSkillItem,
      AboutPageDocumentDataSlicesSlice,
      ArchivePageDocument,
      ArchivePageDocumentData,
      ArchivePageDocumentDataSlicesSlice,
      GlobalSettingDocument,
      GlobalSettingDocumentData,
      GlobalSettingDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ListingOrderProjectDocument,
      ListingOrderProjectDocumentData,
      ListingOrderProjectDocumentDataListOrtderProjectsItem,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      VirtuallightPageDocument,
      VirtuallightPageDocumentData,
      VirtuallightPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutRichtextSlice,
      AboutRichtextSliceDefaultPrimary,
      AboutRichtextSliceVariation,
      AboutRichtextSliceDefault,
      AboutSkillSlice,
      AboutSkillSliceDefaultPrimarySkillListItem,
      AboutSkillSliceDefaultPrimary,
      AboutSkillSlice2ColumnsPrimarySkillListLeftItem,
      AboutSkillSlice2ColumnsPrimarySkillListRightItem,
      AboutSkillSlice2ColumnsPrimary,
      AboutSkillSliceVariation,
      AboutSkillSliceDefault,
      AboutSkillSlice2Columns,
      ArchiveListingSlice,
      ArchiveListingSliceDefaultPrimaryListMediaItem,
      ArchiveListingSliceDefaultPrimary,
      ArchiveListingSliceVariation,
      ArchiveListingSliceDefault,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      ProjectListingSlice,
      ProjectListingSliceDefaultPrimaryFeatureProjectsItem,
      ProjectListingSliceDefaultPrimary,
      ProjectListingSliceVariation,
      ProjectListingSliceDefault,
      ProjectSliceSlice,
      ProjectSliceSliceDefaultPrimary,
      ProjectSliceSliceSingleImagePrimary,
      ProjectSliceSliceListImagePrimaryListImagesItem,
      ProjectSliceSliceListImagePrimary,
      ProjectSliceSliceDetailPrimaryListContentItem,
      ProjectSliceSliceDetailPrimary,
      ProjectSliceSliceEmbedVideoPrimary,
      ProjectSliceSliceGridLayoutPrimaryListImageItem,
      ProjectSliceSliceGridLayoutPrimary,
      ProjectSliceSliceVideoGridLayoutPrimaryListVideoItem,
      ProjectSliceSliceVideoGridLayoutPrimary,
      ProjectSliceSliceVariation,
      ProjectSliceSliceDefault,
      ProjectSliceSliceSingleImage,
      ProjectSliceSliceListImage,
      ProjectSliceSliceDetail,
      ProjectSliceSliceEmbedVideo,
      ProjectSliceSliceGridLayout,
      ProjectSliceSliceVideoGridLayout,
      SpacingSlice,
      SpacingSliceDefaultPrimary,
      SpacingSliceVariation,
      SpacingSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceResumePrimaryListSkillItem,
      TextBlockSliceResumePrimaryListContactItem,
      TextBlockSliceResumePrimary,
      TextBlockSliceRichtextPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockSliceResume,
      TextBlockSliceRichtext,
      VirtualLightCompSlice,
      VirtualLightCompSliceDefaultPrimaryListImageItem,
      VirtualLightCompSliceDefaultPrimaryListInternalMediaItem,
      VirtualLightCompSliceDefaultPrimaryListEmbedMediaItem,
      VirtualLightCompSliceDefaultPrimary,
      VirtualLightCompSliceGridLayoutPrimaryListMediaItem,
      VirtualLightCompSliceGridLayoutPrimary,
      VirtualLightCompSliceVariation,
      VirtualLightCompSliceDefault,
      VirtualLightCompSliceGridLayout,
      VituralightRecognizedPotentialSlice,
      VituralightRecognizedPotentialSliceDefaultPrimaryListMemberItem,
      VituralightRecognizedPotentialSliceDefaultPrimary,
      VituralightRecognizedPotentialSliceVariation,
      VituralightRecognizedPotentialSliceDefault,
      VituralightSliceSlice,
      VituralightSliceSliceDefaultPrimary,
      VituralightSliceSliceGridLayoutPrimaryListMediaItem,
      VituralightSliceSliceGridLayoutPrimary,
      VituralightSliceSliceEmbedPrimary,
      VituralightSliceSlice2ColumnsPrimary,
      VituralightSliceSliceVariation,
      VituralightSliceSliceDefault,
      VituralightSliceSliceGridLayout,
      VituralightSliceSliceEmbed,
      VituralightSliceSlice2Columns,
    };
  }
}
