// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_richtext: dynamic(() => import("./AboutRichtext")),
  about_skill: dynamic(() => import("./AboutSkill")),
  archive_listing: dynamic(() => import("./ArchiveListing")),
  image_block: dynamic(() => import("./ImageBlock")),
  marquee: dynamic(() => import("./Marquee")),
  project_listing: dynamic(() => import("./ProjectListing")),
  project_slice: dynamic(() => import("./ProjectSlice")),
  spacing: dynamic(() => import("./Spacing")),
  text_block: dynamic(() => import("./TextBlock")),
  vituralight_recognized_potential: dynamic(
    () => import("./VituralightRecognizedPotential"),
  ),
  vituralight_slice: dynamic(() => import("./VituralightSlice")),
};
