// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_richtext: dynamic(() => import("./AboutRichtext")),
  about_skill: dynamic(() => import("./AboutSkill")),
  image_block: dynamic(() => import("./ImageBlock")),
  project_listing: dynamic(() => import("./ProjectListing")),
  text_block: dynamic(() => import("./TextBlock")),
};
