// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_richtext: dynamic(() => import("./AboutRichtext")),
  about_skill: dynamic(() => import("./AboutSkill")),
  archive_listing: dynamic(() => import("./ArchiveListing")),
  image_block: dynamic(() => import("./ImageBlock")),
  project_detail_slices: dynamic(() => import("./ProjectDetailSlices")),
  project_image: dynamic(() => import("./ProjectImage")),
  project_listing: dynamic(() => import("./ProjectListing")),
  project_slice: dynamic(() => import("./ProjectSlice")),
  text_block: dynamic(() => import("./TextBlock")),
  virtual_light_comp: dynamic(() => import("./VirtualLightComp")),
};
